#!/usr/bin/env python3
"""Produce ONE specimen of every document the Auralis system creates in operation.

Purpose: hand a designer (or Claude Design) the complete set of artefacts a
client, the practice, or a partner ever receives — so the visual layer can be
reworked in one pass and returned as templates.

Every specimen is generated by the REAL production code path with realistic
sample data. Nothing here is a mock-up: what you see is what a client gets.

Emails are extracted from the .eml into standalone HTML with the inline logo
turned into a data: URI, so each one opens and renders in any browser.

    python3 portal/tools/build_doc_specimens.py [out_dir]

Writes a directory plus a ZIP beside it. Uses only sample data — never a real
client record.
"""
from __future__ import annotations
import base64
import datetime as dt
import json
import re
import shutil
import sys
import zipfile
from email import message_from_bytes
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
import os
# Specimens must show the PRODUCTION addresses. Locally, config.json still says
# 127.0.0.1:5056 — a designer copying that into a template would ship a dead link.
os.environ.setdefault("AURALIS_PUBLIC_BASE_URL", "https://api.auralisnatura.com")
from lib import cfg, render, mailer, booking, social, socialrender  # noqa: E402
cfg.reset_caches()

OUT = Path(sys.argv[1] if len(sys.argv) > 1
           else "/tmp/Auralis-Dokumente")
STAMP = dt.date.today().isoformat()

# ── sample data — a plausible client, never a real one ───────────────────────
NAME = "Elena Martín"
EMAIL = "elena.martin@example.com"
CID = "AN-0042"
WHEN_DE = booking.format_when("2026-08-26T08:05:00+00:00", "de")
SLOT = "2026-08-26T08:05:00+00:00"

MANIFEST: list[dict] = []


def note(folder: str, filename: str, title: str, audience: str,
         trigger: str, source: str) -> None:
    MANIFEST.append({"folder": folder, "file": filename, "title": title,
                     "audience": audience, "trigger": trigger, "source": source})


def d(sub: str) -> Path:
    p = OUT / sub
    p.mkdir(parents=True, exist_ok=True)
    return p


def eml_to_html(msg, out: Path) -> None:
    """Standalone HTML from an email: the cid: logo becomes a data: URI so the
    file renders on its own — a designer should not need a mail client."""
    html_part, images = None, {}
    for part in msg.walk():
        ct = part.get_content_type()
        if ct == "text/html" and html_part is None:
            html_part = part.get_content()
        elif part.get_content_maintype() == "image":
            cid = (part.get("Content-ID") or "").strip("<>")
            if cid:
                images[cid] = (part.get_content_type(),
                               base64.b64encode(part.get_payload(decode=True)).decode())
    body = html_part or "<p>(kein HTML-Teil)</p>"
    for cid, (mime, b64) in images.items():
        body = body.replace(f"cid:{cid}", f"data:{mime};base64,{b64}")
    subj = msg["Subject"] or ""
    head = (f'<div style="max-width:560px;margin:0 auto 18px;padding:14px 16px;'
            f'background:#ECE2CE;border:1px solid rgba(61,39,25,.14);'
            f'font:13px/1.5 -apple-system,Helvetica,Arial,sans-serif;color:#5C4A3A">'
            f'<b style="color:#281F16">Betreff:</b> {subj}<br>'
            f'<b style="color:#281F16">An:</b> {msg["To"] or ""}'
            + (f'<br><b style="color:#281F16">Cc:</b> {msg["Cc"]}' if msg["Cc"] else "")
            + '</div>')
    out.write_text(
        '<!doctype html><html lang="de"><head><meta charset="utf-8">'
        f'<title>{subj}</title></head>'
        f'<body style="margin:0;padding:24px 12px;background:#DFD6C4">{head}{body}</body></html>',
        encoding="utf-8")


# ═══════════════════════════════════════════════ 1 · Kundinnen-E-Mails ══
print("· Kundinnen-E-Mails")
F = "01-Kundinnen-E-Mails"
ics_intro = booking.ics_for(SLOT, NAME, "BK-MUSTER", client_email=EMAIL, language="de")

specs = [
    ("01-Buchung-Eingangsbestaetigung.html",
     mailer.build_ack_email(EMAIL, NAME, WHEN_DE, "de", "BK-MUSTER"),
     "Eingangsbestätigung", "Kundin",
     "Sekunden nach dem Absenden des Buchungsformulars — sofort gesendet",
     "mailer.build_ack_email"),
    ("02-Termin-Bestaetigung.html",
     mailer.build_booking_email(EMAIL, NAME, WHEN_DE, "de", ics_intro, "BK-MUSTER", SLOT),
     "Termin-Bestätigung mit Kalender-Einladung", "Kundin",
     "Nach Prüfung durch Desiree — liegt als Entwurf im Postfach",
     "mailer.build_booking_email"),
    ("03-Termin-Erinnerung.html",
     mailer.build_reminder_email(EMAIL, NAME, WHEN_DE, "de", SLOT, ics_intro),
     "Termin-Erinnerung", "Kundin",
     "Auf Knopfdruck aus der Konsole vor dem Gespräch",
     "mailer.build_reminder_email"),
    ("05-Zugangsdaten-Portal.html",
     mailer.build_credentials_email(EMAIL, NAME, CID, "Kf7pQr2mXw", "de",
                                    "https://api.auralisnatura.com/portal#k=BEISPIEL"),
     "Zugangsdaten zum Klienten-Portal", "Kundin",
     "Wenn Desiree die Kundin gewinnt und den Portalzugang ausstellt",
     "mailer.build_credentials_email"),
    ("08-Feedback-Anfrage.html",
     mailer.build_feedback_email(EMAIL, NAME, "de"),
     "Feedback- & Testimonial-Anfrage", "Kundin",
     "Nach Abschluss des Programms — schließt den Empfehlungskreis",
     "mailer.build_feedback_email"),
    ("09-Newsletter.html",
     mailer.build_newsletter(
         "Drei Impulse für deinen Spätsommer",
         "Hallo,\n\nzwischen Urlaub und Alltag liegt oft eine Woche, in der alles "
         "wieder in den alten Rhythmus rutscht. Drei kleine Dinge, die dabei helfen, "
         "das Gute mitzunehmen …\n\nHerzlich,\nDesiree",
         [EMAIL]),
     "Newsletter an aktive Kundinnen", "Kundinnen (BCC)",
     "Wenn Desiree ihn in der Konsole schreibt",
     "mailer.build_newsletter"),
]
for fname, msg, title, aud, trig, src in specs:
    eml_to_html(msg, d(F) / fname)
    note(F, fname, title, aud, trig, src)

# programme schedule + cancellation need session data
sessions = [
    {"id": "s1", "utc": "2026-09-01T08:00:00+00:00", "minutes": 60, "key": "kickoff", "n": 1},
    {"id": "s2", "utc": "2026-09-08T08:00:00+00:00", "minutes": 45, "key": "weekly", "n": 2},
    {"id": "s3", "utc": "2026-09-15T08:00:00+00:00", "minutes": 45, "key": "weekly", "n": 3},
    {"id": "s4", "utc": "2026-09-22T08:00:00+00:00", "minutes": 45, "key": "weekly", "n": 4},
]
ics_prog = booking.sessions_ics(sessions, NAME, EMAIL, "de", cid=CID)
eml_to_html(mailer.build_sessions_email(EMAIL, NAME, sessions, "de", "Wandel", CID, ics_prog),
            d(F) / "06-Programm-Terminplan.html")
note(F, "06-Programm-Terminplan.html", "Programm-Terminplan mit Sammel-Einladung", "Kundin",
     "Wenn Desiree die Gespräche eines gekauften Programms plant",
     "mailer.build_sessions_email")

ics_cancel = booking.sessions_ics([sessions[2]], NAME, EMAIL, "de", cid=CID, cancel=True)
eml_to_html(mailer.build_session_cancel_email(EMAIL, NAME, sessions[2], "de", ics_cancel),
            d(F) / "04-Termin-Absage.html")
note(F, "04-Termin-Absage.html", "Termin-Absage (entfernt den Eintrag aus dem Kalender)",
     "Kundin", "Wenn Desiree einen Programm-Termin absagt",
     "mailer.build_session_cancel_email")

# report delivery mail needs a PDF to attach
print("· Kundinnen-Bericht")
SECS = [
    {"key": "starting_point", "title": "Dein Ausgangspunkt",
     "body": "Du bist mit einem klaren Wunsch gekommen: wieder Energie für deinen Alltag. "
             "Seit Monaten fühlst du dich erschöpft, obwohl du nach eigener Einschätzung genug "
             "schläfst — und genau diese Diskrepanz ist der wichtigste Hinweis in deinem "
             "gesamten Aufnahmebogen.\n"
             "Deine Selbsteinschätzung zeigt Energie bei 2 von 5 und Stress bei 4 von 5. "
             "Zusammen mit deiner Lebensphase ergibt das ein stimmiges Bild, mit dem wir "
             "arbeiten können.",
     "science": "Anhaltende Erschöpfung trotz ausreichender Schlafdauer hängt in Studien "
                "häufig mit Eisenstatus, Schilddrüsenparametern und chronischer "
                "Stressbelastung zusammen — Bereiche, die sich gut beobachten lassen.",
     "actions": ["Zwei Wochen ein kurzes Energie-Tagebuch führen (morgens, mittags, abends)",
                 "Beim nächsten Arzttermin Ferritin und TSH ansprechen"]},
    {"key": "what_were_seeing", "title": "Was wir sehen",
     "body": "Drei Muster fallen auf: die Schere zwischen Energie und Stress, der unruhige "
             "Schlaf in der zweiten Nachthälfte und die Verdauung, die auf anstrengende Tage "
             "reagiert.\nKeines dieser Muster ist für sich ungewöhnlich. Ihre Kombination "
             "erzählt aber eine klare Geschichte über dein Nervensystem.",
     "science": "Das autonome Nervensystem verbindet alle drei Beobachtungen: die "
                "Cortisol-Tagesrhythmik beeinflusst Schlafarchitektur und Darmbewegung "
                "gleichermaßen.",
     "actions": ["Abends zehn Minuten ohne Bildschirm vor dem Schlafengehen",
                 "Mittagessen ohne Nebenbeschäftigung — fünfzehn Minuten nur essen"]},
    {"key": "the_science_simply", "title": "Die Wissenschaft, einfach",
     "body": "Energie entsteht in den Mitochondrien, den Kraftwerken deiner Zellen. Sie "
             "brauchen zuverlässig drei Dinge: Sauerstoff, Mikronährstoffe und Pausen.\n"
             "Fehlt eines davon dauerhaft, sinkt die Ausbeute — und genau das spürst du am "
             "Nachmittag.",
     "science": "Der Citratzyklus benötigt B-Vitamine, Magnesium und Eisen als Kofaktoren; "
                "ein Mangel bremst die ATP-Produktion messbar.",
     "actions": ["Protein zum Frühstück, etwa 25 bis 30 Gramm",
                 "Zwei Handvoll grünes Gemüse täglich",
                 "Koffein nach 14 Uhr weglassen"]},
    {"key": "your_plan", "title": "Dein Plan",
     "body": "Wir beginnen bewusst klein: drei Prioritäten, ein Rhythmus, kein Programm.\n"
             "Woche eins und zwei gehören dem Schlaffenster. Woche drei ergänzt das "
             "Frühstück. In Woche vier schauen wir gemeinsam auf dein Energie-Tagebuch.",
     "science": "Verhaltensforschung zeigt: die Erfolgswahrscheinlichkeit neuer Gewohnheiten "
                "steigt deutlich, wenn höchstens zwei Änderungen parallel laufen.",
     "actions": ["Festes Schlaffenster von 23:00 bis 07:00",
                 "Frühstück nach dem Protein-Prinzip",
                 "Wöchentlicher Kurz-Check im Portal"]},
    {"key": "when_to_see_a_doctor", "title": "Wann zur Ärztin",
     "body": "Coaching ergänzt medizinische Versorgung — es ersetzt sie nie. Bitte vereinbare "
             "einen Arzttermin, wenn eines der folgenden Zeichen auftritt oder anhält.\n"
             "Unerklärlicher Gewichtsverlust, Brustschmerzen oder Atemnot, anhaltend starke "
             "Schmerzen, Ohnmacht — und generell alles, was dir Sorgen macht.",
     "science": "", "actions": ["Bei diesen Zeichen: ärztliche Abklärung zuerst",
                                "Im Notfall: 112"]},
    {"key": "next_steps", "title": "Deine nächsten Schritte",
     "body": "Nimm dir aus diesem Bericht genau eine Sache — die leichteste. Beginne heute "
             "damit.\nIn unserem Besprechungsgespräch gehen wir alles gemeinsam durch, "
             "beantworten deine Fragen und passen den Plan an dein echtes Leben an.",
     "science": "", "actions": ["Den Bericht einmal in Ruhe lesen",
                                "Eine Frage notieren, die dir wichtig ist",
                                "Termin für das Besprechungsgespräch wählen"]},
]
REP = {"priorities": [
    {"title": "Schlaffenster stabilisieren", "why": "Der größte Hebel für deine Energie.",
     "first_step": "Heute Abend um 23:00 Uhr."},
    {"title": "Protein zum Frühstück", "why": "Stabilisiert Blutzucker und Vormittagsenergie.",
     "first_step": "Morgen: Eier oder Skyr."},
    {"title": "Stress-Mikropausen", "why": "Drei Minuten senken die Tagesanspannung messbar.",
     "first_step": "Timer um 11 und um 16 Uhr."}],
    "weekly_plan": {"mon": "Schlaffenster ab heute", "tue": "Protein-Frühstück",
                    "wed": "Zehn Minuten Tageslicht am Morgen", "thu": "Mikropause 11 und 16 Uhr",
                    "fri": "Grünes Gemüse doppelt", "sat": "Bewegung, die Freude macht",
                    "sun": "Rückblick: was war leicht?"},
    "habits": ["Schlaffenster 23–7", "Protein-Frühstück", "Tageslicht am Morgen",
               "Mikropausen", "Koffein-Stopp um 14 Uhr"]}
CHARTS = {"energy": 2, "sleep": 3, "stress": 4, "digestion": 3}
PROFILE = {"symptoms": ["fatigue", "sleep", "stress"]}

R = "03-Kundinnen-Bericht"
for lang, label in (("de", "deutsch"), ("en", "englisch"), ("es", "spanisch")):
    doc = render.build_html(NAME, SECS, charts=CHARTS, language=lang,
                            report=REP, profile=PROFILE)
    (d(R) / f"Bericht-{lang}.html").write_text(doc, encoding="utf-8")
    render.to_pdf(doc, d(R) / f"Bericht-{lang}.pdf")
    note(R, f"Bericht-{lang}.pdf", f"Persönlicher Gesundheitsbericht ({label})", "Kundin",
         "Nach Freigabe durch Desiree — das Herzstück jedes Pakets",
         "render.build_html + render.to_pdf")
    note(R, f"Bericht-{lang}.html", f"Bericht-Quelldatei ({label}) — hier lässt sich das "
         f"Layout bearbeiten", "Designquelle", "—", "render.build_html")

pdf_de = d(R) / "Bericht-de.pdf"
eml_to_html(mailer.build_email(EMAIL, NAME, pdf_de, "de"), d(F) / "07-Bericht-Zustellung.html")
note(F, "07-Bericht-Zustellung.html", "Bericht-Zustellung (mit PDF im Anhang)", "Kundin",
     "Wenn der freigegebene Bericht erzeugt wird", "mailer.build_email")

# ═════════════════════════════════════════════════ 2 · Interne E-Mails ══
print("· Interne E-Mails")
I = "02-Interne-E-Mails"
profile = {"goal": "Wieder Energie für meinen Alltag finden — ich bin seit Monaten "
                   "erschöpft, obwohl ich genug schlafe.",
           "symptoms": ["fatigue", "sleep", "cycle"], "since": "months", "age": 34,
           "life_stage": "perimenopause",
           "scales": {"energy": 2, "sleep": 3, "stress": 4, "digestion": 3},
           "tried": "Mehr Sport, weniger Kaffee — beides hält nie lange.",
           "red_flags": ["none"]}
eml_to_html(mailer.build_internal_booking_email(NAME, EMAIL, WHEN_DE, "de", profile,
                                                "Ich freue mich auf das Gespräch.", "BK-MUSTER",
                                                ics_intro),
            d(I) / "10-Neue-Buchung-Briefing.html")
note(I, "10-Neue-Buchung-Briefing.html", "Briefing zu einer neuen Buchung",
     "Praxis (team@)", "Sekunden nach jeder Buchung — sofort gesendet",
     "mailer.build_internal_booking_email")

# ══════════════════════════════════════════════════ 4 · Kalender (.ics) ══
print("· Kalender-Einladungen")
K = "04-Kalender-Einladungen"
(d(K) / "Kennenlerngespraech.ics").write_bytes(ics_intro)
(d(K) / "Programm-Termine.ics").write_bytes(ics_prog)
(d(K) / "Termin-Absage.ics").write_bytes(ics_cancel)
note(K, "Kennenlerngespraech.ics", "Kalender-Einladung Kennenlerngespräch", "Kundin",
     "Hängt an der Termin-Bestätigung und am internen Briefing", "booking.ics_for")
note(K, "Programm-Termine.ics", "Sammel-Einladung: alle Programm-Gespräche", "Kundin",
     "Hängt am Programm-Terminplan — einmal annehmen, alle Termine stehen",
     "booking.sessions_ics")
note(K, "Termin-Absage.ics", "Absage (entfernt den Termin aus dem Kalender)", "Kundin",
     "Hängt an der Absage-Mail", "booking.sessions_ics(cancel=True)")

# ═══════════════════════════════════════════════════ 5 · Social Media ══
print("· Social-Media-Bilder")
S = "05-Social-Media"
v_quote = {"headline": "Müdigkeit ist ein Signal — kein Charakterzug",
           "sub": "Was anhaltende Erschöpfung über Eisen, Schlaf und Stress verraten kann."}
v_myth = {"myth": "Müdigkeit nach 40 ist einfach normal.",
          "fact": "Anhaltende Erschöpfung hat messbare Ursachen — hinschauen lohnt sich."}
v_tips = {"headline": "Vier Dinge, die deinen Vormittag tragen",
          "items": ["Morgens zehn Minuten Tageslicht", "Protein zum Frühstück",
                    "Koffein nach 14 Uhr weglassen", "Abends den Bildschirm dimmen"]}
v_car = {"slides": [{"kicker": "Wissen der Woche", "title": "Eisen & Energie",
                     "body": "Warum Ferritin mehr sagt als Hämoglobin — und wann Werte täuschen."}]
         + [{"title": t, "body": b} for t, b in [
             ("Was Ferritin misst", "Den Speicher, nicht den Transport. Deshalb kann Hämoglobin normal sein."),
             ("Wann es täuscht", "Bei Entzündung steigt Ferritin — ein hoher Wert ist dann kein voller Speicher."),
             ("Was das für dich heißt", "Werte gehören eingeordnet, nicht nur abgelesen."),
             ("Der nächste Schritt", "Beim nächsten Termin Ferritin ansprechen — und den Kontext mitdenken.")]]}
v_story = {"question": "Was raubt dir gerade am meisten Energie?"}
v_reel = {"title": "Drei Energie-Impulse für deine Woche",
          "outro": "Folge @auralis_natura für Wissenschaft, warm erklärt."}

W, H = socialrender.SIZES["post"]
SW, SH = socialrender.SIZES["story"]
socialrender.to_png(socialrender.tpl_quote(v_quote, W, H), d(S) / "post-zitat.png", W, H)
socialrender.to_png(socialrender.tpl_mythfact(v_myth, W, H), d(S) / "post-mythos-fakt.png", W, H)
socialrender.to_png(socialrender.tpl_tips(v_tips, W, H), d(S) / "post-tipps.png", W, H)
for i in range(5):
    socialrender.to_png(socialrender.tpl_carousel_slide(v_car, i, 5, W, H),
                        d(S) / f"karussell-{i + 1}.png", W, H)
socialrender.to_png(socialrender.tpl_story(v_story, SW, SH), d(S) / "story.png", SW, SH)
socialrender.to_png(socialrender.tpl_reel_card(v_reel, "title", SW, SH),
                    d(S) / "reel-titel.png", SW, SH)
socialrender.to_png(socialrender.tpl_reel_card(v_reel, "outro", SW, SH),
                    d(S) / "reel-outro.png", SW, SH)
for f, t in [("post-zitat.png", "Zitat-/Impulskarte 1080×1350"),
             ("post-mythos-fakt.png", "Mythos-Fakt-Karte 1080×1350"),
             ("post-tipps.png", "Tipps-/Checklisten-Karte 1080×1350"),
             ("karussell-1.png", "Karussell-Cover (dunkel) 1080×1350"),
             ("karussell-2.png", "Karussell-Folgeslide 1080×1350"),
             ("story.png", "Story-Fläche mit Platz für den Frage-Sticker 1080×1920"),
             ("reel-titel.png", "Reel-Titelkarte 1080×1920"),
             ("reel-outro.png", "Reel-Abspann 1080×1920")]:
    note(S, f, t, "Instagram-Publikum", "Auf Knopfdruck „Bilder erzeugen“ je Slot",
         "socialrender.tpl_*")

slot = {"id": "slot-01", "kind": "post", "day": "Mittwoch", "time": "09:00",
        "caption_de": "Müdigkeit ist ein Signal — kein Charakterzug.\n\nWenn du seit Monaten "
                      "erschöpft bist, obwohl du genug schläfst, lohnt sich der zweite Blick: "
                      "auf Eisenspeicher, auf deinen Schlafrhythmus, auf die Belastung, die "
                      "du gerade trägst.\n\nDu brauchst dafür keine neue Disziplin. Du brauchst "
                      "Zusammenhänge, die sichtbar werden.",
        "caption_en": "Tiredness is a signal — not a character trait.\n\nIf you have been "
                      "exhausted for months despite sleeping enough, a second look is worth it: "
                      "at iron stores, at your sleep rhythm, at the load you are carrying.",
        "caption_es": "El cansancio es una señal, no un rasgo de carácter.\n\nSi llevas meses "
                      "agotada aunque duermas suficiente, merece la pena mirar de nuevo.",
        "hashtags": ["#frauengesundheit", "#erschöpfung", "#eisenmangel", "#perimenopause",
                     "#ganzheitlichegesundheit", "#barcelona"],
        "alt_text": "Zitatkarte im Auralis-Design mit dem Satz „Müdigkeit ist ein Signal — "
                    "kein Charakterzug“."}
(d(S) / "captions.txt").write_text(
    f"SLOT slot-01 · POST · Mittwoch 09:00\n{'=' * 46}\n\n"
    f"CAPTION (einfügen wie sie ist):\n\n{social.assemble_caption(slot)}\n\n"
    f"ALT-TEXT:\n{slot['alt_text']}\n", encoding="utf-8")
(d(S) / "README-Checkliste.txt").write_text(
    social._CHECKLIST.format(week="2026-W35"), encoding="utf-8")
note(S, "captions.txt", "Fertige Caption (DE/EN/ES gestapelt) + Alt-Text",
     "Desiree → Instagram", "Liegt in jedem Wochenpaket-ZIP", "social.assemble_caption")
note(S, "README-Checkliste.txt", "Checkliste zum Planen in Meta Business Suite",
     "Desiree", "Liegt in jedem Wochenpaket-ZIP", "social._CHECKLIST")

eml_to_html(mailer.build_social_package_email(
    "2026-W35", {"slots": [dict(slot, approved=True)]}), d(I) / "11-Social-Wochenpaket.html")
note(I, "11-Social-Wochenpaket.html", "Social-Wochenpaket mit allen freigegebenen Posts",
     "Praxis (team@)", "Auf Knopfdruck „Paket an team@ mailen“",
     "mailer.build_social_package_email")

# ══════════════════════════════════════════════════════ 6 · DSGVO ══
print("· DSGVO-Datenauskunft")
G = "06-Datenauskunft-DSGVO"
(d(G) / "Datenauskunft-Beispiel.json").write_text(json.dumps({
    "client_id": CID, "exported": f"{STAMP}T09:00",
    "stammdaten": {"name": NAME, "email": EMAIL, "sprache": "de",
                   "login_id": "elena.martin", "angelegt": "2026-08-14"},
    "einwilligungen": {"coaching_not_medical": True, "gdpr_health_data": True,
                       "version": "1.0"},
    "buchungen": [{"id": "BK-MUSTER", "zeitpunkt": SLOT, "status": "confirmed"}],
    "aufnahmebogen": {"goal": profile["goal"], "b": profile["scales"],
                      "hinweis": "vollständig, verschlüsselt gespeichert"},
    "bericht": {"stand": "freigegeben", "sprache": "de"},
    "aktivitaet": [{"ts": "2026-08-14T08:05", "event": "call booked"},
                   {"ts": "2026-08-14T08:20", "event": "credentials issued & emailed"}],
}, ensure_ascii=False, indent=2), encoding="utf-8")
note(G, "Datenauskunft-Beispiel.json", "Datenauskunft nach Art. 15 DSGVO",
     "Kundin auf Anfrage", "Auf Knopfdruck in der Konsole", "app.gdpr_export")

# ═══════════════════════════════════════════════════ 7 · Anleitungen ══
print("· Anleitungen & Handbücher")
A = "07-Anleitungen-und-Handbuecher"
HANDOVER = cfg.ROOT.parent / "handover" / "auralis-portal"
for src, title, aud in [
    ("SOCIAL-MEDIA-ANLEITUNG.pdf", "Social-Media-Manager live schalten", "Desiree / Betrieb"),
    ("OPERATOR-ONBOARDING.pdf", "Einarbeitung: der Prozess Station für Station", "Desiree / Betrieb"),
    ("OPERATIONS-MANUAL.pdf", "Technisches Betriebshandbuch (Server, Tunnel, Backup)", "Betrieb / IT"),
    ("CUSTOMER-APP-BUILD-GUIDE.pdf", "Kunden-App: Build & Auslieferung", "Betrieb / IT"),
    ("APP-STORE-ONE-PAGER.pdf", "App Store: der Weg zur Veröffentlichung", "Desiree / Betrieb"),
]:
    p = HANDOVER / src
    if p.exists():
        shutil.copy2(p, d(A) / src)
        note(A, src, title, aud, "Bestandsdokument — bei Änderungen neu erzeugt",
             f"handover/auralis-portal/{src}")

# ═════════════════════════════════════════════════════════ index ══
print("· Übersicht")
by_folder: dict[str, list[dict]] = {}
for m in MANIFEST:
    by_folder.setdefault(m["folder"], []).append(m)

FOLDER_TITLES = {
    "01-Kundinnen-E-Mails": ("An die Kundin", "Alles, was eine Klientin je von Auralis "
                             "im Posteingang findet — von der ersten Sekunde nach der "
                             "Buchung bis zur Bitte um Feedback."),
    "02-Interne-E-Mails": ("An die Praxis", "Was der Server an team@ schickt, damit "
                           "Desiree den Überblick behält, ohne in die Konsole zu schauen."),
    "03-Kundinnen-Bericht": ("Das Herzstück", "Der persönliche Gesundheitsbericht in "
                             "allen drei Sprachen — als fertiges PDF und als bearbeitbare "
                             "HTML-Quelle."),
    "04-Kalender-Einladungen": ("Kalender", "Echte Einladungen (METHOD:REQUEST), die "
                                "Termine automatisch in den Kalender der Kundin legen "
                                "und dort auch wieder entfernen."),
    "05-Social-Media": ("Instagram", "Die Bildvorlagen der Visual Factory in Originalgröße, "
                        "dazu die fertige Caption und die Planungs-Checkliste."),
    "06-Datenauskunft-DSGVO": ("Rechtliches", "Die vollständige Datenauskunft, die eine "
                               "Kundin nach Art. 15 DSGVO verlangen kann."),
    "07-Anleitungen-und-Handbuecher": ("Für den Betrieb", "Die Dokumente, die niemand außer "
                                       "dem Auralis-Team liest — Einarbeitung und Technik."),
}

rows = ""
for folder in sorted(by_folder):
    title, desc = FOLDER_TITLES.get(folder, (folder, ""))
    rows += (f'<h2><span class="fnum">{folder.split("-")[0]}</span>{title}</h2>'
             f'<p class="fdesc">{desc}</p><table><tr><th>Dokument</th><th>Empfänger</th>'
             f'<th>Wann es entsteht</th></tr>')
    for m in sorted(by_folder[folder], key=lambda x: x["file"]):
        rows += (f'<tr><td><a href="{folder}/{m["file"]}">{m["title"]}</a>'
                 f'<div class="fn">{m["file"]}</div></td>'
                 f'<td>{m["audience"]}</td><td>{m["trigger"]}'
                 f'<div class="src">{m["source"]}</div></td></tr>')
    rows += "</table>"

seal = base64.b64encode((cfg.ASSETS_DIR / "seal.png").read_bytes()).decode()
(OUT / "00-LIESMICH.html").write_text(f"""<!doctype html><html lang="de"><head>
<meta charset="utf-8"><title>Auralis Natura — Dokumenten-Übersicht</title>
<style>
*{{box-sizing:border-box;margin:0;padding:0;border-radius:0}}
body{{font:15px/1.6 -apple-system,"Helvetica Neue",Arial,sans-serif;color:#5C4A3A;
background:#F5EEE0;padding:40px 20px}}
.wrap{{max-width:900px;margin:0 auto}}
header{{text-align:center;padding:28px 0 34px;border-bottom:1px solid rgba(173,122,50,.42);margin-bottom:30px}}
header img{{width:84px;height:84px}}
h1{{font-family:Georgia,serif;font-weight:400;font-size:2.1rem;color:#281F16;margin:16px 0 8px}}
.kick{{font-size:.66rem;letter-spacing:.3em;text-transform:uppercase;color:#A8492A;font-weight:700}}
.lead{{max-width:60ch;margin:12px auto 0}}
h2{{font-family:Georgia,serif;font-weight:400;font-size:1.4rem;color:#3D2719;
margin:34px 0 4px;display:flex;align-items:baseline;gap:12px}}
.fnum{{font-size:1rem;color:#AD7A32}}
.fdesc{{margin-bottom:12px;color:#75685A}}
table{{width:100%;border-collapse:collapse;background:#FBF6EB;border:1px solid rgba(61,39,25,.14)}}
th{{text-align:left;font-size:.62rem;letter-spacing:.16em;text-transform:uppercase;
color:#75685A;padding:9px 12px;border-bottom:1px solid rgba(61,39,25,.26);background:#ECE2CE}}
td{{padding:10px 12px;border-bottom:1px solid rgba(61,39,25,.14);vertical-align:top;font-size:.9rem}}
td:first-child{{width:38%}}
a{{color:#A8492A;text-decoration:none;font-weight:600}}
a:hover{{text-decoration:underline}}
.fn{{font-family:ui-monospace,Menlo,monospace;font-size:.72rem;color:#8C7E6E;margin-top:2px}}
.src{{font-family:ui-monospace,Menlo,monospace;font-size:.7rem;color:#8C7E6E;margin-top:2px}}
.box{{background:#FBF6EB;border:1px solid rgba(61,39,25,.14);border-left:3px solid #AD7A32;
padding:14px 18px;margin:24px 0}}
.box.warn{{border-left-color:#A8492A;background:#FCF3EF}}
.bt{{font-size:.62rem;letter-spacing:.16em;text-transform:uppercase;color:#75685A;
font-weight:700;margin-bottom:6px}}
ul{{margin:6px 0 0 18px}} li{{margin:4px 0}}
footer{{margin-top:40px;padding-top:16px;border-top:1px solid rgba(61,39,25,.14);
font-size:.78rem;color:#75685A;text-align:center}}
</style></head><body><div class="wrap">
<header>
  <img src="data:image/png;base64,{seal}" alt="">
  <div class="kick">Auralis Natura</div>
  <h1>Jedes Dokument, das das System erzeugt</h1>
  <p class="lead">{len(MANIFEST)} Belegstücke, erzeugt vom echten Produktivcode mit
  Beispieldaten. Was hier steht, ist genau das, was eine Kundin bekommt.</p>
</header>

<div class="box">
  <div class="bt">Wie du damit arbeitest</div>
  <ul>
    <li><b>E-Mails</b> sind eigenständige HTML-Dateien — im Browser öffnen, das Logo ist
        eingebettet. Oben steht grau, an wen sie geht und mit welchem Betreff.</li>
    <li><b>Der Bericht</b> liegt doppelt vor: als PDF (so sieht ihn die Kundin) und als
        HTML (dort lässt sich das Layout bearbeiten).</li>
    <li><b>Social-Bilder</b> sind in Originalgröße — 1080×1350 für Posts und Karussells,
        1080×1920 für Stories und Reels.</li>
    <li><b>.ics-Dateien</b> haben kein Aussehen; sie steuern, wie der Termin im Kalender
        der Kundin erscheint. Für ein Redesign nicht relevant, der Vollständigkeit halber dabei.</li>
  </ul>
</div>

<div class="box warn">
  <div class="bt">Was es noch nicht gibt</div>
  <ul>
    <li><b>Rechnung.</b> Bisher erzeugt das System keine. Das ist bewusst offen, bis das
        Format mit dem Gestor abgestimmt ist (IVA-Behandlung, Pflichtangaben) — sobald das
        geklärt ist, gehört sie genau hierher.</li>
    <li><b>Angebot / Vertrag.</b> Ebenfalls offen; die Pakete werden derzeit im Gespräch
        vereinbart und über Stripe bezahlt.</li>
    <li><b>Lieferanten und Agenturen.</b> Das System hat heute keine Dokumente für diese
        Empfänger — es gibt in der Praxis keinen solchen Prozess. Falls einer entsteht,
        ist der Rahmen (Marke, Schriften, Vorlagen) bereits da.</li>
  </ul>
</div>

{rows}

<footer>Auralis Natura · Betriebssystem der Praxis · Stand {STAMP}<br>
Beispieldaten. Keine Angaben einer echten Klientin.</footer>
</div></body></html>""", encoding="utf-8")

# ═══════════════════════════════════════════════════════════ zip ══
zip_path = OUT.with_suffix(".zip")
zip_path.unlink(missing_ok=True)
with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
    for p in sorted(OUT.rglob("*")):
        if p.is_file():
            z.write(p, f"{OUT.name}/{p.relative_to(OUT)}")

n = sum(1 for p in OUT.rglob("*") if p.is_file())
print(f"\n{n} Dateien · {len(MANIFEST)} Dokumente im Verzeichnis")
print(f"{zip_path}  ({zip_path.stat().st_size // 1024} KB)")
